# using SendGrid's Python Library
# https://github.com/sendgrid/sendgrid-python
import os

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from config.base import settings
from core.utils.otp_and_password_html import create_otp_template

sendgrid_key = settings.SENDGRID_API_KEY


def send_email(to_email, title=None, subject=None, action=None, message1=None, message2=None, action_url=None, support_url=None):
   """
   This function sends email to the specified email address using sendgrid API.
   
   Args:
      to_email (str): The email address of the recipient.
      title (str): The title of the email. Example: "Reset Password".
      subject (str): The subject of the email.
      action (str): This is an optional argument which is used to to generate a anchor tag for the email.
      action_url (str): This is an optional argument. This url is used in the anchor tag generated by providing the action argument.
      message1 (str): Message to send to the email address
      message2 (str): Message to send to the email address
      support_url (str): Url or contact email of the sender.
      
   Returns:
      res : Response object
   """
   
   send_grid = SendGridAPIClient(api_key=sendgrid_key)
   html_content = create_otp_template(title=title, subject=subject, action=action, message1=message1, message2=message2, action_url=action_url, support_url=support_url)
   data = format_mail_data(to_email, subject, html_content)
   res = send_grid.client.mail.send.post(request_body=data)
   return res


def format_mail_data(to_email, subject, html_content):
   return {
      "personalizations": [{"to": [{"email": to_email}], "subject":subject}],
      "from": {"email": settings.SENDGRID_EMAIL, "name": "sendgrid"},
      "content": [{"type": "text/html", "value": html_content}],
   }

